In [2]:
class Parent:
    ## Data member/ATTRIBUTE
    a=90
    b="String"

    ## Member function/Method
    def working(s):      # mandatory parameter self/s/f/b
        print("I am class's method")
obj=Parent() 


In [4]:
obj.working()

I am class's method


In [8]:
l1=10

In [9]:
type(l1)

int

### OOPs
- classes
- objects
- inheritance
- polymorphism
- encapsulation
- abstration


## Numpy
- vector   1-D ARRAY
- matrix   >1-D ARRAY

### 1-D ARRAY

In [11]:
!pip install numpy
# VS Code Terminal/Pycharm/Command Prompt: pip install numpy

In [12]:
import numpy as np

### Methods to create an arrays 
- array()    - list,tuple
- arange()   - create an array within a particular range
- linspace() - provide no. of values within the range
- ones()     - provide ones array
- zeroes()   - provide zeroes array
- eye()      - provide identity matrix
- random     - rand, randint,uniform

In [24]:
list1=[1,2,3,4,5,6.90]
arr=np.array(list1)
print(arr)

[1.  2.  3.  4.  5.  6.9]


In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.dtype

dtype('float64')

In [23]:
arr1=np.array((67,34,23))
print(arr1)

[67 34 23]


In [50]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(list2)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
arr2[0:3,0]

array([1, 4, 7])

In [33]:
arr2[1][1]

5

In [34]:
arr2.ndim    # dimentions

2

In [35]:
arr2.shape      # rows and col

(3, 3)

In [41]:
### Ones array
arr3=np.ones((3,4),dtype='int')              # ones(row,col,dtype='int')
print(arr3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [40]:
### Ones array
arr3=np.ones((3,4),dtype='int')*55              # ones(row,col,dtype='int')
print(arr3)

[[55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]]


In [42]:
### Ones array
arr3=np.ones((3,4))             # ones(row,col,dtype='int')
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
list2=[[[[1,2,3],[4,5,6],[7,8,9]]]]
arr2=np.array(list2)
print(arr2)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [44]:
arr2.ndim

4

In [49]:
arr2[0][0][2][2]

9

In [ ]:
## create an array -- identity, arange, linspace

In [52]:
arr4=np.eye(3,3,dtype='int')
print(arr4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [53]:
arr4=np.eye(3,3,dtype='int')*555
print(arr4)

[[555   0   0]
 [  0 555   0]
 [  0   0 555]]


In [57]:
arr5=np.arange(1,10)
print(arr5)

[1 2 3 4 5 6 7 8 9]


In [58]:
arr5.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr6=np.linspace(3,5,10)
print(arr6)

[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]


In [65]:
arr6.size

50

### Random array
- randint              - array of random integer in a specific range
- rand                 - array of random in bt 0-1
- uniform              - array of random decimal no.in a specific range

In [1]:
import numpy as np

In [6]:
arr6=np.random.rand(4,5)
arr6.ndim

2

In [8]:
arr7=np.random.rand(3,4,5)
arr7.ndim

3

In [15]:
arr8=np.random.randint(10,50,size=(2,6))
arr8

array([[12, 23, 28, 36, 49, 47],
       [30, 20, 39, 45, 32, 11]])

In [17]:
import numpy.random as rd
from numpy import random as rd

In [18]:
arr9=rd.uniform(20,30,size=(4,4))
arr9

array([[24.9520546 , 22.34309839, 24.90135222, 28.14102688],
       [24.77522132, 25.88739212, 28.66809359, 22.92096853],
       [27.26634655, 23.79522319, 26.56122312, 28.92649166],
       [26.17503548, 29.36815212, 22.03154706, 27.04164206]])

### Array operations
- sum()
- min()
- max()
- sqrt()
- mean()
- std()
- argmax()
  

In [19]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
arr10=np.array(list2)
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.sum(arr10)              # arr10.sum()

45

In [22]:
arr10.sum(axis=0)

array([12, 15, 18])

In [25]:
arr10.min(axis=0)

array([1, 2, 3])

In [28]:
np.std(arr10)

2.581988897471611

In [31]:
# mean, sqrt
arr10.mean()
np.sqrt(arr10)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [32]:
arr10.argmax()

8

### Pandas
- Seris           - 1D
- DataFrame        - 2D

!pip install pandas

In [33]:
import pandas as pd

In [43]:
list1=[1,2,3,4,5,6,7]
sr=pd.Series(list1)
print(sr)
type(sr)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


pandas.core.series.Series

In [41]:
df=sr.to_frame()
print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7


In [42]:
type(df)

pandas.core.frame.DataFrame

### Methods to create dataframe
- List of lists
- List of tuple
- Tuple of tuples
- Tuple of lists
- List of dictionaries
- dictionary of lists
- read_excel()
- read_csv()
- read_json()
- json_normalize
- read_html()

In [49]:
dict2={
        "Temp":[12,34,56,21,0],
        "Hum":[45,33,12,22,12],
       "Event": ["Rainy","Sunny","Sunny","Cloudy","Snow"]
}

In [50]:
weather=pd.DataFrame(list2)
weather

Temp  Hum   Event
0    12   45   Rainy
1    34   33   Sunny
2    56   12   Sunny
3    21   22  Cloudy
4     0   12    Snow

In [51]:
list2=[
    [12,45,"Rainy"],
    [34,33,"Sunny"]
    
]

In [53]:
df1=pd.DataFrame(list2,columns=["Temp ","Hum","Event"])
df1

Temp  Hum  Event
0    12   45  Rainy
1    34   33  Sunny

In [55]:
!pip install html5lib

   ---------------------------------------- 0.0/112.2 kB ? eta -:--:--
   --- ------------------------------------ 10.2/112.2 kB ? eta -:--:--
   ---------- ----------------------------- 30.7/112.2 kB 1.3 MB/s eta 0:00:01
   -------------------------------- ------- 92.2/112.2 kB 1.1 MB/s eta 0:00:01
   ---------------------------------- --- 102.4/112.2 kB 980.4 kB/s eta 0:00:01
   -------------------------------------- 112.2/112.2 kB 653.4 kB/s eta 0:00:00


In [60]:
html=pd.read_html("https://en.wikipedia.org/wiki/Economy_of_India")
df4=html[3]

In [62]:
df4.to_csv("economy.csv") 

In [67]:
csv=pd.read_csv("D://Mody University/4th Sem/Notes/Practicals/Supervised ML/Salary_Data.csv")

In [71]:
csv.head(10)

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891
5              2.9  23.0   56642
6              3.0  23.0   60150
7              3.2  23.3   54445
8              3.2  23.3   64445
9              3.7  23.6   57189

In [70]:
csv.tail()

YearsExperience   Age  Salary
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [76]:
weather.to_json("wth.json")

In [77]:
jdata=pd.read_json("wth.json")
jdata

Temp  Hum   Event
0    12   45   Rainy
1    34   33   Sunny
2    56   12   Sunny
3    21   22  Cloudy
4     0   12    Snow

In [78]:
jdata["Event"]

0     Rainy
1     Sunny
2     Sunny
3    Cloudy
4      Snow
Name: Event, dtype: object

In [79]:
jdata[["Temp","Event"]]

Temp   Event
0    12   Rainy
1    34   Sunny
2    56   Sunny
3    21  Cloudy
4     0    Snow

In [82]:
jdata.loc[1:2,["Temp","Hum"]]

Temp  Hum
1    34   33
2    56   12

In [84]:
jdata.iloc[1:3:1,0:2:1]         #iloc[strt_row:last_row:step,strt_col:last_col:step]

Temp  Hum
1    34   33
2    56   12

In [86]:
jdata[jdata["Temp"]>45]

Temp  Hum  Event
2    56   12  Sunny

In [88]:
jdata.describe()

Temp        Hum
count   5.000000   5.000000
mean   24.600000  24.800000
std    21.512787  14.237275
min     0.000000  12.000000
25%    12.000000  12.000000
50%    21.000000  22.000000
75%    34.000000  33.000000
max    56.000000  45.000000

In [2]:
import numpy as np
import pandas as pd

In [3]:
list2=[
    [12,45,"Rainy",np.nan],
    [34,33,"Sunny",23]
    
]

In [4]:
df7=pd.DataFrame(list2)

In [5]:
df7

0   1      2     3
0  12  45  Rainy   NaN
1  34  33  Sunny  23.0

In [ ]:
df7[4]=[]

In [94]:
df7.isnull().sum()

0    0
1    0
2    0
3    1
dtype: int64

In [98]:
df7.fillna(df7[3].median())

0   1      2     3
0  12  45  Rainy  23.0
1  34  33  Sunny  23.0

In [99]:
df7.fillna(0)

0   1      2     3
0  12  45  Rainy   0.0
1  34  33  Sunny  23.0